name: Dynamic Gradle Build Matrix

on:
    push:

jobs:
    generate-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - uses: actions/checkout@v2
            - id: set-matrix
              run: |
                  echo "::set-output name=matrix::$(python3 versions.py)"

    build:
        needs: generate-matrix
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                  java-version: '17'
                  distribution: 'adopt'

            - name: Update Gradle Properties
              run: |
                  echo "org.gradle.jvmargs=${{ matrix.HEAP_GRADLE }} ${{ matrix.GC_GRADLE }} -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1g" >> gradle.properties
                  echo "kotlin.daemon.jvmargs=-${{ matrix.HEAP_KOTLIN }} ${{ matrix.KC_GRADLE }}" >> gradle.properties
                  echo "org.gradle.workers.max=${{ matrix.WORKERS }}" >> gradle.properties
                  cat gradle.properties
                  ./gradlew :help  -Dscan.tag.W_${{ matrix.WORKERS }}  -Dscan.tag.HK_${{ matrix.HEAP_KOTLIN }} -Dscan.tag.HG_${{ matrix.HEAP_GRADLE }} -Dscan.tag.GG_${{ matrix.GC_GRADLE }} -Dscan.tag.GK_${{ matrix.KC_GRADLE }} -Dscan.tag.${{ matrix.REPETITION }}
              env:
                GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}

