name: Dynamic Gradle Build Matrix

on:
    push:

jobs:
    generate-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - id: set-matrix
              run: |
                  echo "::set-output name=matrix::$(python3 versions.py)"

    build:
        needs: generate-matrix
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'

            - name: Update Gradle Properties
              run: |
                  echo "org.gradle.jvmargs=${{ matrix.HEAP_GRADLE }} ${{ matrix.GC_GRADLE }} -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1g" >> gradle.properties
                  echo "kotlin.daemon.jvmargs=-${{ matrix.HEAP_KOTLIN }} ${{ matrix.GC_KOTLIN }}" >> gradle.properties
                  echo "org.gradle.workers.max=${{ matrix.WORKERS }}" >> gradle.properties

            - name: Build with Gradle
              run: ./gradlew :help

